### ISSUE TITLE
Problems with extensions FailedTestsReporter

### ISSUE THREAD

**Issue by rossokhinDaniil** [Codeception/robo-paracept#103]
Hello! Found problems in the FailedTestsReporter extension. This extension saves the path to cases without the first character. Does this make sense or is it a bug? The problem is in this line:
https://github.com/Codeception/robo-paracept/blob/10bbd3b13043e68c645aea646b6fd89cb9c76e02/src/Extension/FailedTestsReporter.php#L68

**Comment by jmrieger** [comment]
@DavertMik - Would you be able to elaborate what the original intent of the substr replace was? I was trying to read the unit test, but also noted that the `getTestName` function was mocked in the test and isn't covered. I assume the intent is to remove the leading slash, and if that's the case, I can open a patch for it.

**Comment by reinholdfuereder** [comment]
(Disclaimer: I have never used this code/extension; so my comment might be really useless)

https://github.com/Codeception/Codeception/blob/be148b9494dc9136bf2dea4094a78d0219bd58b9/src/Codeception/Extension.php#L145

https://github.com/Codeception/Codeception/blob/be148b9494dc9136bf2dea4094a78d0219bd58b9/src/Codeception/Configuration.php#L543

=> This really looks like there is a `DIRECTORY_SEPARATOR` that needs to be replaced!?

**Comment by jmrieger** [comment]
@reinholdfuereder That's what I was seeing as well. I assume the original intent was to strip that leading DIRECTORY_SEPARATOR. I have only been working on testing this for my own use case, and I didn't see documentation of what else could be expecting that.

I suppose in either case, something like this should be a safe means to handle the separator being present (or not, as it seems to always be the case):

```php
        return ltrim(str_replace($this->getRootDir(), '', $name), '/');
```
