### ISSUE TITLE
Packagist not synchronized with github

### ISSUE THREAD

**Issue by eXorus** [Codeception/robo-paracept#11]
Hello,

Dependencies are fixed in the last master version of robo-paracept in Github (require robo 0.7.0)

But according to this page : https://packagist.org/packages/codeception/robo-paracept
robo-paracept require robo 0.6.0.

So it's failed because composer use packagist to retrieve the last version.

@DavertMik could you please synchronize it ? Thanks

**Comment by DavertMik** [comment]
Thanks Done
