### ISSUE TITLE
Reference to missing class `\Codeception\PHPUnit\Init`

### ISSUE THREAD

**Issue by StuTheWebGuy** [Codeception/robo-paracept#113]
## Overview

There's a [reference](https://github.com/Codeception/robo-paracept/blob/master/src/Splitter/TestsSplitter.php#L208) to the `\Codeception\PHPUnit\Init` class here, but using the latest stable versions of both this package and `codeception/codeception` results in this class going missing.

The class in question comes from [`codeception/phpunit-wrapper`](https://github.com/Codeception/phpunit-wrapper/blob/9.0/src/Init.php), which isn't included with, and cannot be installed alongside, Codeception.

The lastest version of `codeception/codeception` 5.x prevents the installation of `codeception/phpunit-wrapper` by `replace`ing the dependency in its [composer.json](https://github.com/Codeception/Codeception/blob/5.0/composer.json#L68).

So currently it's impossible through latest stable channels to run this code.

## Steps to reproduce

1. Install `codeception/codeception:^5.0` and `codeception/robo-paracept:^2.0`.
2. Follow the steps (up to and including Setting Up Robo // Step 1: Split Tests) in the [Codeception Parallel Execution documentation](https://codeception.com/docs/ParallelExecution).
3. Try to run `php vendor/bin/robo parallel:split-tests`.

## Workarounds

I believe you can create your own version of the missing class and write an empty `init()` method, because the code in the original PHPUnit wrapper `init()` method isn't required anyway. As long as it can be autoloaded and run, it should bypass this issue.

Currently I've got the latest stable `codeception/codeception`, but capped `robo-paracept` to version 1.2.4, which is the last release without the missing class reference.

## References

[Previously mentioned](https://github.com/Codeception/robo-paracept/pull/112#issuecomment-1264238951) in #112

**Comment by vansari** [comment]
@StuTheWebGuy Please try the new Version 2.1 which does not use this init method anymore.
