### ISSUE TITLE
Tag 2.1.0 dependencies too strict

### ISSUE THREAD

**Issue by route33** [Codeception/robo-paracept#121]
The newly released tag 2.1.0 for PHP 8.0, codeception 5 and Symfony components 6.0 is too strict. It requires version 6.0.0 and nothing above it, for example 6.0.11

Is there any reason for that?

Thank you

**Comment by vansari** [comment]
@route33 No there is no reason for that. The contraint was too strict. Thanks a lot for your issue.

**Comment by vansari** [comment]
@route33 the Version is updated now to 2.1.1 with less restricted versions
