### ISSUE TITLE
TaskIO used in tasks, while BaseTask already uses it

### ISSUE THREAD

**Issue by gdscei** [Codeception/robo-paracept#19]
The TaskIO trait is already used in Robo's BaseTask, but both are used in the tasks. This creates the following error:

ERROR: Robo\Task\BaseTask and Robo\Common\TaskIO define the same property ($config) in the composition of Codeception\Task\TestsSplitter. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed

**Comment by DavertMik** [comment]
Thanks for the fix
