### ISSUE TITLE
Occasionally a test process exits with status code 135 because of a SIGBUS

### ISSUE THREAD

**Issue by ironsmile** [Codeception/robo-paracept#28]
I have a set up which is pretty much the one explained in the [Codeception documentation](http://codeception.com/docs/12-ParallelExecution#Robo). With robo and robo-paracept for running tests.

While using it one of the processes for running Codeception would fail with an exit code 135. Here is an output from such an incident:

```
 [ParallelExec] Output for ../vendor/bin/codecept run --skip-group api --group parallel_4 --xml paracept/_results/result_4.xml acceptance:

Codeception PHP Testing Framework v2.2.7
Powered by PHPUnit 4.8.31 by Sebastian Bergmann and contributors.
[Groups] parallel_4 
 [ParallelExec]  Exit code 135  Time 01:54
```

There is no other output from the process. Now, this error code 135 is very suspicious. So I went ahead and investigated further. In the [Symfony/Process](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Process/Process.php#L1524) one can see that this exit code is only possible in two cases:

1. The process (codeception in our case) has exited with exit code 135
```php
$this->exitcode = $this->processInformation['exitcode'];
```

2. The process has received a signal from the OS with the numerical value of 7:
```
$this->exitcode = 128 + $this->processInformation['termsig'];
```

We can rule out the first case since Codeception exits with 0 or 1 and nothing else. So we are left with the hypothesis that a signal stops the process. The signal with numerical value 7 is "SIGBUS". One can verify that by running `kill -l` which would print all signals and their numerical values.

So why would that happen? Trying to find out what the problem is I found [PHP bug 52752](https://bugs.php.net/bug.php?id=52752). It is still open and impacts all PHP versions up to and including 7.

So, is this our problem? I set up the environment so that a core dump file would be generated for the php process when an abortion signal is received. And sure enough, the next time our tests failed with status code 135, the same back trace as the one in the bug report is found. See the last few lines of it:

```
#0  0x00007f2097dd86ed in lex_scan ()
#1  0x00007f2097df7062 in zendlex ()
#2  0x00007f2097dd1956 in zendparse ()
#3  0x00007f2097dd6f5b in compile_file ()
#4  0x00007f2097dfd12a in dtrace_compile_file ()
#5  0x00007f2085d7bc9a in phar_compile_file () from /usr/lib64/php/modules/phar.so
#6  0x00007f2097ec08b3 in ZEND_INCLUDE_OR_EVAL_SPEC_CV_HANDLER ()
#7  0x00007f2097e39e68 in execute_ex ()
#8  0x00007f2097dfd1a9 in dtrace_execute_ex ()
#9  0x00007f2097ec27cb in zend_do_fcall_common_helper_SPEC ()
#10 0x00007f2097e39e68 in execute_ex ()
#11 0x00007f2097dfd1a9 in dtrace_execute_ex ()
#12 0x00007f2097ec27cb in zend_do_fcall_common_helper_SPEC ()
#13 0x00007f2097e39e68 in execute_ex ()
#14 0x00007f2097dfd1a9 in dtrace_execute_ex ()
#15 0x00007f2097ec27cb in zend_do_fcall_common_helper_SPEC ()
#16 0x00007f2097e39e68 in execute_ex ()
#17 0x00007f2097dfd1a9 in dtrace_execute_ex ()
```

Basically, this happens when the PHP interpreter reads a source file while this file is being edited. In the bug report there is a one liner which reproduces the bug.

_The following is just a hypothesis_

So how do we end up triggering this bug? My suspicion is that the reason is the code which Codeception generates. I am talking about the file `support/_generated/AcceptanceTesterActions.php`. It seems to be programatically created and then used while running a Codeception Cest test. The guess goes like this: every process invoked by robo-paracept tries to write in the same file and then uses it. Most of the time this is fine because all processes do create functionally the same file but this fails from time to time because of the PHP bug 52752.

**Why am I writing here?**

As far as I can tell this is not really a problem in robo-paracept. It is just a curious side effect of the way Codeception works grouped with the PHP bug. But one can argue that Codeception alone would never hit this so it is robo-paracept which have to do something about it.

_But this is a PHP bug, just wait for it to be fixed._ Well, the bug is quite old already and I don't see it being fixed anytime soon. It has been 7 years since it was reported and two (one? PHP 6 got skipped?) major versions of the language have been released since then. In the meantime robo-paracept is bound to fail occasionally.

_You should've created this issue in the Codeception project._ Maybe I should have. If you think that it should be there, then I would move it.

**Proposed solution**

I have only limited understanding of Codeception. Mainly, I do understand how it decides its exit code 😄  But if robo-paracept can be made to invoke Codeception in a way that different generated files would be created for every parallel process.

An other way would be to stop using generated files altogether in Codeception. But I have no idea what this entails.

**Environment:**

OS: CentOS Linux 7.3
Codeception: v2.2.7
robo-paracept: v0.2
robo: v1.0.5
PHP: v5.5.38

**Additional data**

I can supply you with the mentioned coredump and binary with which it happened if this is of any help. Or I can create a minimal example which hits this bug. But the [one in the example](http://codeception.com/docs/12-ParallelExecution#Robo) should be more than enough. Actually, most of the robo-paracept usage is bound to be susceptible to this issue. I've seen it happen dozens of times a day to once every other day.

**Comment by ironsmile** [comment]
I don't know if it is of any importance, but the issue is still present after upgrading to **PHP 5.6.30**. Which is only natural if my hypothesis for the root cause is correct.

**Comment by cebe** [comment]
Thanks for writing such a detailed report, helped me a lot to understand a similar problem with Symfony/Process!

**Comment by ironsmile** [comment]
You are welcome, @cebe . And your commend reminds me that this bug was actually fixed few months ago and this issue can be closed.
