### ISSUE TITLE
If parallel exec fails and no report produced MergeHTMLReportsTask throws an error

### ISSUE THREAD

**Issue by CABellamy** [Codeception/robo-paracept#31]
Parallel Exec fails with exit code 138 and does not produce a HTML report when merging the reports this is throwing an uncaught exception. 

ERROR: Uncaught Error: Call to a member function appendChild() on null in /Users/.../vendor/codeception/robo-paracept/src/MergeReports.php:269
Stack trace:
#0 /Users/.../vendor/codeception/robo-paracept/src/MergeReports.php(211): Codeception\Task\MergeHTMLReportsTask->moveSummaryTable(Object(DOMDocument), NULL)
#1 /Users/.../vendor/consolidation/robo/src/Collection/CollectionBuilder.php(428): Codeception\Task\MergeHTMLReportsTask->run()
#2 /Users/.../vendor/consolidation/robo/src/Collection/CollectionBuilder.php(413): Robo\Collection\CollectionBuilder->runTasks()
#3 /Users/.../Project/Gaming-Codeception/gaming-codeception/src/Robo.php(64): Robo\Collection\CollectionBuilder->run()
#4 /Users/.../Project/Gaming-Codeception/gaming-codeception/src/Robo.php(75): Gaming\Codeception\Robo->parallelMergeResults()
#5 [
in /Users/.../vendor/codeception/robo-paracept/src/MergeReports.php:269

**Comment by virus-found** [comment]
Agreed. Terribly annoying.

**Comment by hadouke** [comment]
Try to add codecept.phar file to the root.
That helped me.

**Comment by rostislaw9** [comment]
Is it ever going to be fixed?

**Comment by vansari** [comment]
@CABellamy & @rostislaw9 
Can you please check https://github.com/Codeception/robo-paracept/pull/85
I think it would be helpful if the process prints a task warning if a report was expected but not found or was not readable.
