### ISSUE TITLE
Since PHPUnit 6 Parallel:Split-Tests has stopped working

### ISSUE THREAD

**Issue by CABellamy** [Codeception/robo-paracept#35]
Splitting tests now fails since the upgrade to PHPUnit6. Running taskSplitTestsByGroups throws the following error:

ERROR: Interface 'PHPUnit_Framework_Test' not found
in /project/vendor/codeception/base/src/Codeception/TestInterface.php:7

Call Stack:
    0.0010     356648   1. {main}() /ProjectDir/ui-tests/vendor/consolidation/robo/robo:0
    0.0103     949600   2. Robo\Runner->execute() /ProjectDir/ui-tests/vendor/consolidation/robo/robo:20
    0.0265    1649712   3. Robo\Runner->run() /ProjectDir/ui-tests/vendor/consolidation/robo/src/Runner.php:111
    0.1245    4442688   4. Symfony\Component\Console\Application->run() /ProjectDir/ui-tests/vendor/consolidation/robo/src/Runner.php:157
    0.1419    4443520   5. Symfony\Component\Console\Application->doRun() /ProjectDir/ui-tests/vendor/symfony/console/Application.php:130
    0.1421    4443520   6. Symfony\Component\Console\Application->doRunCommand() /ProjectDir/ui-tests/vendor/symfony/console/Application.php:223
    0.1458    4470032   7. Symfony\Component\Console\Command\Command->run() /ProjectDir/ui-tests/vendor/symfony/console/Application.php:887
    0.1476    4482768   8. Consolidation\AnnotatedCommand\AnnotatedCommand->execute() /ProjectDir/ui-tests/vendor/symfony/console/Command/Command.php:264
    0.1480    4559112   9. Consolidation\AnnotatedCommand\CommandProcessor->process() /ProjectDir/ui-tests/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:394
    0.1480    4559168  10. Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter() /ProjectDir/ui-tests/vendor/consolidation/annotated-command/src/CommandProcessor.php:119
    0.1493    4574088  11. Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback() /ProjectDir/ui-tests/vendor/consolidation/annotated-command/src/CommandProcessor.php:153
    0.1494    4575160  12. call_user_func_array:{/ProjectDir/ui-tests/vendor/consolidation/annotated-command/src/CommandProcessor.php:207}() /ProjectDir/ui-tests/vendor/consolidation/annotated-command/src/CommandProcessor.php:207
    0.1494    4575568  13. Gaming\Codeception\Robo->parallelSplitTests() /ProjectDir/ui-tests/vendor/consolidation/annotated-command/src/CommandProcessor.php:207
    0.1496    4576000  14. Robo\Collection\CollectionBuilder->run() /ProjectDir/ui-tests/vendor/gaming/codeception/src/Robo.php:43
    0.1500    4583928  15. Robo\Collection\CollectionBuilder->runTasks() /ProjectDir/ui-tests/vendor/consolidation/robo/src/Collection/CollectionBuilder.php:413
    0.1500    4583928  16. Codeception\Task\SplitTestsByGroupsTask->run() /ProjectDir/ui-tests/vendor/consolidation/robo/src/Collection/CollectionBuilder.php:428
    0.1575    5114592  17. Codeception\Test\Loader->loadTests() /ProjectDir/ui-tests/vendor/codeception/robo-paracept/src/SplitTestsByGroups.php:78
    0.1575    5114592  18. Codeception\Test\Loader->loadTest() /ProjectDir/ui-tests/vendor/codeception/base/src/Codeception/Test/Loader.php:123
    0.1576    5114616  19. Codeception\Test\Loader->loadTests() /ProjectDir/ui-tests/vendor/codeception/base/src/Codeception/Test/Loader.php:113
    0.1699    5414104  20. Codeception\Test\Loader\Cest->loadTests() /ProjectDir/ui-tests/vendor/codeception/base/src/Codeception/Test/Loader.php:135
    0.1721    5503680  21. spl_autoload_call() /ProjectDir/ui-tests/vendor/codeception/base/src/Codeception/Test/Loader/Cest.php:95
    0.1721    5503808  22. Composer\Autoload\ClassLoader->loadClass() /ProjectDir/ui-tests/vendor/codeception/base/src/Codeception/Test/Loader/Cest.php:95
    0.1721    5503968  23. Composer\Autoload\includeFile() /ProjectDir//ui-tests/vendor/composer/ClassLoader.php:322
    0.1726    5549408  24. include('/ProjectDir/ui-tests/vendor/codeception/base/src/Codeception/Test/Cest.php') /ProjectDir/ui-tests/vendor/composer/ClassLoader.php:440
    0.1726    5549408  25. spl_autoload_call() /ProjectDir/ui-tests/vendor/codeception/base/src/Codeception/Test/Cest.php:16
    0.1726    5549536  26. Composer\Autoload\ClassLoader->loadClass() /ProjectDir/ui-tests/vendor/codeception/base/src/Codeception/Test/Cest.php:16
    0.1727    5549696  27. Composer\Autoload\includeFile() /ProjectDir/ui-tests/vendor/composer/ClassLoader.php:322
    0.1731    5567384  28. include('/ProjectDir/ui-tests/vendor/codeception/base/src/Codeception/Test/Test.php') /ProjectDir/ui-tests/vendor/composer/ClassLoader.php:440
    0.1747    5590664  29. spl_autoload_call() /ProjectDir/ui-tests/vendor/codeception/base/src/Codeception/Test/Test.php:17
    0.1747    5590800  30. Composer\Autoload\ClassLoader->loadClass() /ProjectDir/ui-tests/vendor/codeception/base/src/Codeception/Test/Test.php:17
    0.1748    5590960  31. Composer\Autoload\includeFile() /ProjectDir/ui-tests/vendor/composer/ClassLoader.php:322
    0.1750    5592464  32. include('/ProjectDir/ui-tests/vendor/codeception/base/src/Codeception/TestInterface.php') /ProjectDir/ui-tests/vendor/composer/ClassLoader.php:440

Oddly enough taskSplitTestFilesByGroups works fine.

**Comment by maxgorovenko** [comment]
Use this header for your RoboFile
```
<?php
require_once 'vendor/autoload.php';
require_once 'vendor/codeception/codeception/autoload.php';
```
