### ISSUE TITLE
Does not work when codeception is already installed

### ISSUE THREAD

**Issue by graciousgrey** [Codeception/robo-paracept#39]
As written in this documentation http://codeception.com/docs/12-ParallelExecution robo-paracebt does not work when codeception is already installed. 

Will this issue be solved ? 

What is the recommended way to handle this when codeception is already installed? 
I tried: Removing codeception from the composer.json and run composer update --> Add robo-paracebt to composer.json --> composer update --> add codeception to composer.json --> run composer update.

I still get the error  "Neither composer nor phar installation of Codeception found" when I try to execute a robo task. What could be the problem?

**Comment by DavertMik** [comment]
Maybe you could add 

```php
require 'vendor/autoload.php';
```
to RoboFile

**Comment by mariusz-kraj** [comment]
@DavertMik after adding this, we are unable to use robo when vendors are empty and need to use 
`composer install` manually.

**Comment by graciousgrey** [comment]
With`require vendor/autoload.php` I still got the error. 
Setting the path argument to the taskCodeception function `taskCodecept('bin/codecept')` solved the issue for me.

**Comment by vansari** [comment]
Closing... > 3 years old
