### ISSUE TITLE
SplitTestsByGroupsTasks doesn't split properly when using a dataprovider

### ISSUE THREAD

**Issue by CABellamy** [Codeception/robo-paracept#40]
SplitTestsByGroupsTasks task doesn't split tests properly if the tests are using a dataprovider. It uses the fullpath from /vendor/phpunit/phpunit/src/Framework/DataProviderTestSuite.php instead of the test that is using the dataprovider. 

Expected:

Group_1:
tests/Acceptance/Desktop/TestWithDataProvider.php:DataProviderScenario1
tests/Acceptance/Desktop/TestWithDataProvider.php:DataProviderScenario2
tests/Acceptance/Desktop/TestWithDataProvider.php:DataProviderScenario3
tests/Acceptance/Desktop/TestWithDataProvider.php:DataProviderScenario4
...

Got:

/vendor/phpunit/phpunit/src/Framework/DataProviderTestSuite.php:
/vendor/phpunit/phpunit/src/Framework/DataProviderTestSuite.php:
/vendor/phpunit/phpunit/src/Framework/DataProviderTestSuite.php:
/vendor/phpunit/phpunit/src/Framework/DataProviderTestSuite.php:

**Comment by vansari** [comment]
Old Issue which is fixed will now be closed *tadaaa*
