### ISSUE TITLE
Full paths generated in group file created by taskSplitTestsByGroups are not recognized

### ISSUE THREAD

**Issue by richleland** [Codeception/robo-paracept#42]
Issue - `taskSplitTestsByGroups` is generating group files with full paths in them. When I run codecept and specify one of the group files created, it does not recognize any tests listed in those group files, reporting zero acceptance tests.

I'm using the following:

* PHP 7.2.0RC6
* Codeception 2.4.1
* Robo 1.2.3
* robo-paracept 0.4.0

I've got the following in my RoboFile.php:

```php
class RoboFile extends \Robo\Tasks
{
    use \Codeception\Task\SplitTestsByGroups;

    public function parallelSplitTests() {
        $this->taskSplitTestsByGroups(5)
            ->testsFrom('tests')
            ->projectRoot('.')
            ->groupsTo('tests/_data/paracept_')
            ->run();
    }
}
```

Running the robo task:

```
$ ../../vendor/bin/robo parallel:split-tests                                                                                                      10:49:56 AM
 [Codeception\Task\SplitTestsByGroupsTask] Processing 2 tests
 [Codeception\Task\SplitTestsByGroupsTask] Writing tests/_data/paracept_1
 [Codeception\Task\SplitTestsByGroupsTask] Writing tests/_data/paracept_2
```

Contents of paracept_1:

```
Users/rleland/web/tests/codeception-new/tests/acceptance/backend/LoginLogoutCest.php:loginFailsWithInvalidCredentials
```

Running codecept using that group file:

```
$ ../../vendor/bin/codecept run acceptance -g paracept_1                                                                                          10:54:37 AM
Codeception PHP Testing Framework v2.4.1
Powered by PHPUnit 4.8.28 by Sebastian Bergmann and contributors.
[Groups] paracept_1

Acceptance Tests (0) -----------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 92 ms, Memory: 10.00Mb

No tests executed!
```

I see that `taskSplitTestsByGroups` calls `\Codeception\Test\Descriptor::getTestFullName($test)` which yields the full path. Note that if I use `taskSplitTestFilesByGroups` it generates a group file with a relative path, which works fine:

```
$ ../../vendor/bin/codecept run acceptance -g paracept_1                                                                                          10:57:31 AM
Codeception PHP Testing Framework v2.4.1
Powered by PHPUnit 4.8.28 by Sebastian Bergmann and contributors.
[Groups] paracept_1

Acceptance Tests (2) -----------------------------------------------------------------------------------------------------------------------------------------
✔ LoginLogoutCest: Login succeeds with valid credentials (5.14s)
✔ LoginLogoutCest: Login fails with invalid credentials (1.46s)
--------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 7.46 seconds, Memory: 10.00Mb

OK (2 tests, 4 assertions)
```

Any guidance/input would be great.

**Comment by bnpatel1990** [comment]
This is probably not the best approach but gets the work done for me. This is how I use `taskSplitTestsByGroups` and then later perform a cleanup on it. 

so this is how it looks on my end

```
    public function parallelSplitTests()
    {
        $this->taskSplitTestsByGroups($this->count)
            ->projectRoot('.')
            ->testsFrom('tests')
            ->groupsTo('tests/_groups/robo/robo_')
            ->run();
        $this->groupCleanUp();
    }

    public function groupCleanUp()
    {
        foreach (new DirectoryIterator('tests/_groups/robo') as $file) {
            if ($file->isDot()) continue;

            $content = file_get_contents($file->getPathname());
            file_put_contents($file->getPathname(), '');

            $tests = explode("\n", $content);
            foreach ($tests as $test) {
                if (preg_match("/(.*)suite\//", $test))
                    $test = preg_split("/(.*)suite\//", $test) [1];
                file_put_contents($file->getPathname(), $test . "\n", FILE_APPEND | LOCK_EX);
            }
        }
    }
```

**Comment by GrzegorzDrozd** [comment]
Hi,

I did some changes in the way task files are generated and i noticed that issue today. Temporary fix is to add 

`
\Codeception\Configuration::config();
`

into RoboFile.php like this:

`
    /**
     * Split tests into separate groups. Tests are split by file not by test.
     */
    public function parallelSplitTests()
    {
        \Codeception\Configuration::config();

        // Split your tests by files
        $this->taskSplitTestsByGroups($this->numberOfExecutors)
             ->testsFrom('tests/acceptance')
             ->projectRoot('.')
             ->groupsTo('tests/_data/paracept_')
             ->run();
    }
`

I will create PR with fix as soon as I know why this is happening. Side note: it was working fine for me for months and then it stopped. 
It is because codecept_relative_path is resolving paths against project dir and that is not set until `Configuration::config()` is executed.

As I said: I will try to solve that in code as soon as I can.

**Comment by vansari** [comment]
Hi @richleland 

can you please check if the error still exists with the newest version?

**Comment by richleland** [comment]
Hi there - our team has stopped use of PHP altogether and we haven't used codeception/robo-paracept in a few years. I don't have the means to easily test this anymore so someone else will have to give it a whirl.

**Comment by vansari** [comment]
Thanks a lot for your feedback @richleland 

I will close this issue.
