### ISSUE TITLE
Error merging HTML reports

### ISSUE THREAD

**Issue by marcelpra** [Codeception/robo-paracept#49]
I'm getting error when merging html reports:

` [ParallelExec] ../vendor/bin/codecept run unit --group paracept_1 --html html/result_1.html
 [ParallelExec] ../vendor/bin/codecept run unit --group paracept_2 --html html/result_2.html
 [ParallelExec] ../vendor/bin/codecept run unit --group paracept_3 --html html/result_3.html
 [ParallelExec] ../vendor/bin/codecept run unit --group paracept_4 --html html/result_4.html
 [ParallelExec] ../vendor/bin/codecept run unit --group paracept_5 --html html/result_5.html
 5/5 [============================] 100%
 [ParallelExec] 5 processes finished running
 [ParallelExec] Done in 19.795s
 [Codeception\Task\MergeHTMLReportsTask] Merging HTML reports into tests/_output/result_paracept.html
ERROR: Call to a member function item() on null
in ../vendor/codeception/robo-paracept/src/MergeReports.php:319
`

Using codeception/base 3.1.2

Could be fixed by changing line 316 into:
`        $nodes = (new \DOMXPath($dstFile))->query("//div[@class='layout']/table/tbody/tr[contains(@class, 'scenarioRow')]");
`

**Comment by vansari** [comment]
Hi @marcelpra 

could you please check if the error still exists with the newest version?

**Comment by vansari** [comment]
We have released a new version which fix the bug.
