### ISSUE TITLE
Use lastest version of Robo

### ISSUE THREAD

**Issue by AdrienHt** [Codeception/robo-paracept#50]
Lastest version of Robo is 2.0.3. 

Does it possible to use this version ?

**Comment by marden** [comment]
The project seems abandoned.

**Comment by vansari** [comment]
Hi @marden 

a new version with the newest robo version will be released soon.

**Comment by vansari** [comment]
@AdrienHt And @marden 
It's done 
robo-paracept is now available as Version 1.0

**Comment by vansari** [comment]
@DavertMik I think this Ticket can be closed.
