### ISSUE TITLE
"Return value must be of type Codeception\Task\Splitter\TestFileSplitterTask" when splitting the tests after upgrading to version 1.0

### ISSUE THREAD

**Issue by ccsuperstar** [Codeception/robo-paracept#62]
After updating the robo-paracept version, and making the changes indicated in the readme, I get this error when I run the split command
`PHP Fatal error:  Uncaught TypeError: RoboFile::taskSplitTestFilesByGroups(): Return value must be of type Codeception\Task\Splitter\TestFileSplitterTask, Robo\Collection\CollectionBuilder returned in /vendor/codeception/robo-paracept/src/Splitter/TestsSplitterTrait.php:26`

**Comment by DavertMik** [comment]
@vansari could you help with this?

**Comment by vansari** [comment]
Yes of course. I will do it tomorrow evening. @DavertMik

**Comment by vansari** [comment]
Hi @ccsuperstar 

can you please check the fix?
I think the return type was not correct :-)

I forgot to use the union type

**Comment by ccsuperstar** [comment]
It's ok now on splitting tests, thanks!

**Comment by ccsuperstar** [comment]
Could you tell me how to use the GroupFilter?

**Comment by vansari** [comment]
Hi @ccsuperstar 

Could you please open a new issue for this question? I think this would be a new feature. 

Please let us know what you want to do.

Bye 👋

**Comment by ccsuperstar** [comment]
Ok I'll do it!

**Comment by ccsuperstar** [comment]
I can make a PR with my previous code if you want

**Comment by vansari** [comment]
Hi @ccsuperstar 

I think this issue can be closed?!

**Comment by ccsuperstar** [comment]
Yes!
