### ISSUE TITLE
How to use GroupFilter for run only tests failed?

### ISSUE THREAD

**Issue by ccsuperstar** [Codeception/robo-paracept#64]
During a parallel run, there are sometimes tests that fail
It would be interesting to be able to rerun these tests, in parallel too

**Comment by ccsuperstar** [comment]
I've created a PR for this, feel free to send me your feedback!
#65

**Comment by vansari** [comment]
Hi @ccsuperstar 

thanks for the proposal. We have created an extension which collect the failed test in a report file. after a run you have the possibility to split the failed tests into groups with the created report file.

**Comment by ccsuperstar** [comment]
There is still a problem, the file is overwritten with the last value when running in parallel mode, so all failed tests are not there

**Comment by ccsuperstar** [comment]
If I use another file which is a merge of each failed file, it works so it is not blocking

**Comment by vansari** [comment]
> There is still a problem, the file is overwritten with the last value when running in parallel mode, so all failed tests are not there

Oh okay. I will check it.

**Comment by vansari** [comment]
Hi @ccsuperstar 

i have created a PR https://github.com/Codeception/robo-paracept/pull/75 for this issue.

**Comment by ccsuperstar** [comment]
Thanks @vansari !
I've try to use it, but I have this error
` [error]  Class Codeception\Task\Merger\FailedTestsMergerTask does not have a constructor, so you cannot pass any constructor arguments`
Something is missing?

**Comment by ccsuperstar** [comment]
With your last modification, everything works! Thanks a lot
