### ISSUE TITLE
Pass an array to the testsFrom() method

### ISSUE THREAD

**Issue by ccsuperstar** [Codeception/robo-paracept#70]
In the previous version, we could pass an array of paths to the `testsFrom()` method
`->testsFrom(['tests/bdd', 'tests/integration'])`
This is not possible anymore, because testsFrom() only accepts a string, but it is useful when you want to run only some suites.

**Comment by vansari** [comment]
Hi @ccsuperstar 

I can check this evening how we can reimplement this.

Thanks.

**Comment by ccsuperstar** [comment]
I have made this PR #72 
Feel free to give me feedback

**Comment by ccsuperstar** [comment]
I have made this PR #73 Feel free to send me feedbacks
