### ISSUE TITLE
All tests passed, but summary says FAILED

### ISSUE THREAD

**Issue by mrceperka** [Codeception/robo-paracept#94]
Hello,

any idea why headline says FAILED?

![image](https://user-images.githubusercontent.com/22822651/143426639-a57e4521-5d57-4d57-a382-832f06324878.png)

Output of command:
![image](https://user-images.githubusercontent.com/22822651/143426789-5d1f473a-4b33-45c7-bef3-354e35c8a02b.png)

**Comment by mrceperka** [comment]
Ok, it's probably because of this condition:

https://github.com/Codeception/robo-paracept/blob/ca1650ec00baea1b740cba02b9041c79bb64c1c3/src/Merger/HtmlReportMerger.php#L217

**Comment by vansari** [comment]
Yes 🙌 
Thanks, I think skipped tests should not be one of the marker that the tests failed.

**Comment by reinholdfuereder** [comment]
I could not reproduce this problem now and it is already exactly fixed like you suggested: https://github.com/Codeception/robo-paracept/blob/10bbd3b13043e68c645aea646b6fd89cb9c76e02/src/Merger/HtmlReportMerger.php#L237

And actually by @vansari on on 18 Dec 2021 for v2: https://github.com/Codeception/robo-paracept/commit/b7ef6c8497b79040d13119033430e3b2d64cef6e

:-)

**Comment by reinholdfuereder** [comment]
=> So this issue can be closed
